
export const MONTHLY_RATINGS = [
    {
        year:'2022',
        ratings:[
            {
                month_name:'January',
                data_exist:false
            },
            {
                month_name:'Febraury',
                data_exist:true,
                awards:0,
                honours:0,
                overall_rating:5,
              
            },
            {
                month_name:'March',
                data_exist:true,
                awards:0,
                honours:0,
                overall_rating:5,
            },
            {
                month_name:'April',
                data_exist:true,
                awards:0,
                honours:0,
                overall_rating:5,  
            },
            {
                month_name:'May',
                data_exist:true,
                awards:0,
                honours:0,
                overall_rating:5,
            },
            {
                month_name:'June',
                data_exist:true,
                awards:0,
                honours:0,
                overall_rating:5,    
            },
            {
                month_name:'July',
                data_exist:true,
                awards:0,
                honours:0,
                overall_rating:5,
            },
            {
                month_name:'August',
                data_exist:true,
                awards:0,
                honours:0,
                overall_rating:5,
            },
            {
                month_name:'September',
                data_exist:true,
                awards:0,
                honours:0,
                overall_rating:5,
            },
            {
                month_name:'October',
                data_exist:false,
        
            },
            {
                month_name:'November',
                data_exist:true
            },
            {
                month_name:'December',
                data_exist:false
            }
        ]
    },
    {
        year:'2023',
        ratings:[
            {
                month_name:'January',
                data_exist:false
            },
            {
                month_name:'Febraury',
                data_exist:false      
            },
            {
                month_name:'March',
                data_exist:false
            },
            {
                month_name:'April',
                data_exist:false 
            },
            {
                month_name:'May',
                data_exist:true,
                awards:0,
                honours:0,
                overall_rating:5,
            },
            {
                month_name:'June',
                data_exist:false    
            },
            {
                month_name:'July',
                data_exist:true,
                awards:0,
                honours:0,
                overall_rating:5,
            },
            {
                month_name:'August',
                data_exist:false
            },
            {
                month_name:'September',
                data_exist:false
            },
            {
                month_name:'October',
                data_exist:false,
        
            },
            {
                month_name:'November',
                data_exist:false
            },
            {
                month_name:'December',
                data_exist:false
            }
        ]
    }
    
]


