import { NgModule } from '@angular/core';
import { RouterModule, Routes } from '@angular/router';
import { ADD_PITCH, ASSETS_DECLARATION, ATTENDANCE_CALENDAR, DASHBOARD, DIRECTORY, DSR, DSR_DETAILS, DSR_EDIT, ENTREPRENURSHIP, FLOATING_LEAVE, HOLIDAY_CALENDAR, HOME, INTERVIEW, JOBDETAILS, JOB_OPENINGS, LEAVE_DETAILS, MANUAL_PUNCH, MYTRAINING, MY_ASSETS, MY_IDEA, MY_LEAVE, MY_TRAINING, ONGOING_TRAINING, PERFORMANCE, POLICY_DOCUMENTS, PROFILE, PROJECT, PROJECT_DETAILS, PUNCH_LOG, REFER_CANDIDATE, REQUESTED_ASSETS, REQUESTED_TRAINING, TRAINING_DETAILS, TRAINING_DETAILS_TRAINE, UPCOMING_TRAINING } from 'src/app/constant/routes';
import { FeaturesComponent } from './features.component';
import { HomeModule } from './home/home.module';

const routes: Routes = [
  {
    path:'',
    component:FeaturesComponent,
    children:[
      {
        path:'',
        redirectTo:HOME.fullUrl
        
      },
      {
        path:HOME.fullUrl,
        pathMatch:'full',
        loadChildren:()=>import('./home/home.module').then(
          (m)=>HomeModule
        )
      },
      {
        path:PROFILE.fullUrl,
        pathMatch:'full',
        loadChildren:()=>import('./profile/profile.module').then(
          (m)=>m.ProfileModule
        )
      },
      {
        path:DIRECTORY.fullUrl,
        pathMatch:'full',
        loadChildren:()=>import('./directory/directory.module').then(
          (m)=>m.DirectoryModule
        )
      },
      {
        path:ENTREPRENURSHIP.fullUrl,
        pathMatch:'full',
        loadChildren:()=>import('./entrepreneurship/entrepreneurship.module').then(
          (m)=>m.EntrepreneurshipModule
        )

      },
      {
        path:POLICY_DOCUMENTS.fullUrl,
        loadChildren:()=>import('./my-links/my-links.module').then(
          (m)=>m.MyLinksModule
        )
      },
      {
        path:PERFORMANCE.fullUrl,
        loadChildren:()=>import('./performance/performance.module').then(
          (m)=>m.PerformanceModule
        )
      },
      {
        path:`${JOBDETAILS.fullUrl}/:id`,
        loadChildren:()=>import('./job-details/job-details.module').then(
          (m)=>m.JobDetailsModule
        )
      },
      {
        path:ADD_PITCH.fullUrl,
        loadChildren:()=>import('./entrepreneurship/add-pitch/add-pitch.module').then(
          (m)=>m.AddPitchModule)
      },
      {
        path:HOLIDAY_CALENDAR.fullUrl,
        loadChildren:()=>import('./my-links/holiday-calendar/holiday-calendar.module').then(
          (m)=>m.HolidayCalendarModule)
      },
      {
        path:REFER_CANDIDATE.fullUrl,
        loadChildren:()=>import('./refer-friend/referral-list/referral-list.module').then(
          (m)=>m.ReferralListModule
        )
      },
      {
        path:JOB_OPENINGS.fullUrl,
        loadChildren:()=>import('./refer-friend/job-opening/job-opening.module').then(
          (m)=>m.JobOpeningModule
        )
      },
      {
        path:INTERVIEW.fullUrl,
        loadChildren:()=>import('./recruitment/interview/interview.module').then(
          (m)=>m.InterviewModule
        )
      },
      {
        path:MY_TRAINING.fullUrl,
        loadChildren:()=>import('./fresher-training/my-training/my-training.module').then(
          (m)=>m.MyTrainingModule
        )
      },
      {
        path:TRAINING_DETAILS_TRAINE.fullUrl,
        loadChildren:()=>import('./fresher-training/training-details/training-details.module').then(
          (m)=>m.TrainingDetailsModule
        )
      },
      {
        path:DSR.fullUrl,
        loadChildren:()=>import('./dsr/dsr.module').then(
          (m)=>m.DsrModule
        )
      },
      {
        path:UPCOMING_TRAINING.fullUrl,
        loadChildren:()=>import('./training/upcoming-training/upcoming-training.module').then(
          (m)=>m.UpcomingTrainingModule
        )
      },
      {
        path:ONGOING_TRAINING.fullUrl,
        loadChildren:()=>import('./training/ongoing-training/ongoing-training.module').then(
          (m)=>m.OngoingTrainingModule
        )
      },
      {
        path:REQUESTED_TRAINING.fullUrl,
        loadChildren:()=>import('./training/requested-training/requested-training.module').then(
          (m)=>m.RequestedTrainingModule
        )
      },
      {
        path:MYTRAINING.fullUrl,
        loadChildren:()=>import('./training/my-traings/my-traings.module').then(
          (m)=>m.MyTraingsModule
        )
      },
      {
        path:MY_ASSETS.fullUrl,
        loadChildren:()=>import('./assets/my-assets/my-assets.module').then(
          (module)=>module.MyAssetsModule
        )
      },
      {
        path:REQUESTED_ASSETS.fullUrl,
        loadChildren:()=>import('./assets/request-assets/request-assets.module').then(
          (module)=>module.RequestAssetsModule
        )
      },
      {
        path:ASSETS_DECLARATION.fullUrl,
        loadChildren:()=>import('./assets/assets-declaration/assets-declaration.module').then(
          (module)=>module.AssetsDeclarationModule
        )
      },
      {
        path:ATTENDANCE_CALENDAR.fullUrl,
        loadChildren:()=>import('./attendance/attendance-calendar/attendance-calendar.module').then(
        (module)=>module.AttendanceCalendarModule
        )
      },
      {
        path:MANUAL_PUNCH.fullUrl,
        loadChildren:()=>import('./attendance/manual-punch/manual-punch.module').then(
          (module)=>module.ManualPunchModule
        )
      },
      {
        path:PUNCH_LOG.fullUrl,
        loadChildren:()=>import('./attendance/punch-log/punch-log.module').then(
          (module)=>module.PunchLogModule
        )
      },
      {
        path:MY_LEAVE.fullUrl,
        loadChildren:()=>import('./leave/my-leave/my-leave.module').then(
          (module)=>module.MyLeaveModule
        )
      },
      {
        path:FLOATING_LEAVE.fullUrl,
        loadChildren:()=>import('./leave/floating-leave/floating-leave.module').then(
          (module)=>module.FloatingLeaveModule
        )
      },
      {
        path:'ticket',
        loadChildren:()=>import('./ticket/ticket.module').then(
          (module)=>module.TicketModule
        )
      },
      {
        path:DSR_DETAILS.fullUrl,
        loadChildren:()=>import('./dsr/dsr-details/dsr-details.module').then(
          (module)=>module.DsrDetailsModule
        )
      },
      {
        path:PROJECT.fullUrl,
        loadChildren:()=>import('./project/project.module').then(
          (module)=>module.ProjectModule
        )
      },
      {
        path:PROJECT_DETAILS.fullUrl,
        loadChildren:()=>import('./project/project-details/project-details.module').then(
          (module)=>module.ProjectDetailsModule
        )
      },
      {
        path:`${LEAVE_DETAILS.fullUrl}/:id`,
        loadChildren:()=>import('./leave/leave-details/leave-details.module').then(
          (module)=>module.LeaveDetailsModule
        )
      },
      {
        path:TRAINING_DETAILS.fullUrl,
        loadChildren:()=>import('./training/training-details/training-details.module').then(
          (module)=>module.TrainingDetailsModule
        )
      },
      {
        path:MY_IDEA.fullUrl,
        loadChildren:()=>import('./entrepreneurship/my-idea/my-idea.module').then(
          (module)=>module.MyIdeaModule)
      },
      {
        path:DSR_EDIT.fullUrl,
        loadChildren:()=>import('./dsr/edit-dsr/edit-dsr.module').then(
          (module)=>module.EditDsrModule
        )
      }
    ]
  }
];

@NgModule({
  imports: [RouterModule.forChild(routes)],
  exports: [RouterModule]
})
export class FeaturesRoutingModule { }
