export const PROJECT_DROPDOWN = [
  'Training Project React JS',
  'Miscellaneous', 
  'Interview',
];

export const CHOOSE_AM = [ 'Account Manager','Amardeep Rawat','Amit Singh','Anant Agarwal','Aparna Kaushik','Apeksha Mehta']

export const APPROVING_AUTHORITY = ['Aashini Sharma','Aashish Sharma','Aatish Mittal','Abhijeet Bhadouria','Akanksha Singh'];

export var DSR_TABLEDATA:any = [
  {
    s_no: 1,
    emp_name: 'akshat',
    emp_id: '1553',
    email: 'akshat@appinventiv.com',
    employment_type: 'Permanent',
    date: '2023-03-04',
    logged_hr: 2,
    approval_status: 1,
    status: 'submitted',
    link:`/features/dsr-details?data=1`,
    dsr_description: ['this is dsr 1 '],
  },
  {
    s_no: 2,
    emp_name: 'akshat',
    emp_id: '1553',
    email: 'akshat@appinventiv.com',
    employment_type: 'Permanent',
    date: '2023-03-07',
    logged_hr: 15,
    approval_status: 1,
    status: 'Due',
    link:`/features/dsr-details?data=2`,
    dsr_description: ['this is dsr 2'],
  },
  {
    s_no: 3,
    emp_name: 'akshat',
    emp_id: '1553',  
    email: 'akshat@appinventiv.com',
    employment_type: 'Permanent',
    date: '2023-03-08',
    logged_hr: 1,
    approval_status: 2,
    status: 'Due',
    link:`/features/dsr-details?data=3`,
    dsr_description: ['this is dsr 3'],
  },

  {
    s_no: 4,
    emp_name: 'akshat',
    emp_id: '1553',
    email: 'akshat@appinventiv.com',
    employment_type: 'Permanent',
    date: '2023-03-09',
    logged_hr: 10,
    approval_status: 2,
    status: 'Due',
    link:`/features/dsr-details?data=4`,
    dsr_description: ['this is dsr 4'],
  },
  {
    s_no: 5,
    emp_name: 'akshat',
    emp_id: '1553',
    email: 'akshat@appinventiv.com',
    employment_type: 'Permanent',
    date: '2023-03-10',
    logged_hr: 8,
    approval_status: 2,
    status: 'Due',
    link:`/features/dsr-details?data=5`,
    dsr_description: ['this is dsr 5'],
  },
  {
    s_no: 6,
    emp_name: 'akshat',
    emp_id: '1553',
    email: 'akshat@appinventiv.com',
    employment_type: 'Permanent',
    date: '2023-03-11',
    logged_hr: 2,
    approval_status: 3,
    status: 'Due',
    link:`/features/dsr-details?data=6`,
    dsr_description: ['this is dsr 6'],
  },
  {
    s_no: 7,
    emp_name: 'akshat ',
    emp_id: '1553',
    email: 'akshat@appinventiv.com',
    employment_type: 'Permanent',
    date: '2023-03-12',
    logged_hr: 3,
    approval_status: 3,
    status: 'Due',
    link:`/features/dsr-details?data=7`,
    dsr_description: ['this is dsr 7'],
  },
  {
    s_no: 8,
    emp_name: 'akshat ',
    emp_id: '1553',
    email: 'akshat@appinventiv.com',
    employment_type: 'Permanent',
    date: '2023-03-14',
    logged_hr: 5,
    approval_status: 3,
    status: 'Due',
    link:`/features/dsr-details?data=8`,
    dsr_description: ['this is dsr 8'],
  },
  {
    s_no: 9,
    emp_name: 'akshat',
    emp_id: '1553',
    email: 'akshat@appinventiv.com',
    employment_type: 'Permanent',
    date: '2023-03-13',
    logged_hr: 5,
    approval_status: 1,
    status: 'Due',
    link:`/features/dsr-details?data=9`,
    dsr_description: ['this is dsr 9'],
  },
  {
    s_no: 10,
    emp_name: 'akshat',
    emp_id: '1553',
    email: 'akshat@appinventiv.com',
    employment_type: 'Permanent',
    date: '2023-03-15',
    logged_hr: 9,
    approval_status: 1,
    status: 'Submitted',
    link:`/features/dsr-details?data=10`,
    dsr_description: ['this is dsr 10'],
  },
  {
    s_no: 11,
    emp_name: 'akshat',
    emp_id: '1553',
    email: 'akshat@appinventiv.com',
    employment_type: 'Permanent',
    date: '2023-03-4',
    logged_hr: 10,
    approval_status: 2,
    status: 'Due',
    link:`/features/dsr-details?data=11`,
    dsr_description: ['this is dsr 11'],
  },
  {
    s_no: 12,
    emp_name: 'akshat',
    emp_id: '1553',
    email: 'akshat@appinventiv.com',
    employment_type: 'Permanent',
    date: '2023-03-20',
    logged_hr: 3,
    approval_status: 2,
    status: 'Submitted',
    link:`/features/dsr-details?data=12`,
    dsr_description: ['this is dsr 12'],
  },
  {
    s_no: 13,
    emp_name: 'akshat',
    emp_id: '1553',
    email: 'akshat@appinventiv.com',
    employment_type: 'Permanent',
    date: '2023-03-21',
    logged_hr: 4,
    approval_status: 2,
    link:`/features/dsr-details?data=13`,
    dsr_description: ['this is dsr 13'],
  },
  {
    s_no: 14,
    emp_name: 'akshat',
    emp_id: '1553',
    email: 'akshat@appinventiv.com',
    employment_type: 'Permanent',
    date: '2023-03-22',
    logged_hr: 7,
    approval_status: 1,
    link:`/features/dsr-details?data=14`,
    dsr_description: ['this is dsr 14'],
  },
  {
    s_no: 15,
    emp_name: 'akshat',
    emp_id: '1553',
    email: 'akshat@appinventiv.com',
    employment_type: 'Permanent',
    date: '2023-03-24',
    logged_hr: 15,
    approval_status: 1,
    status: 'Submitted',
    link:`/features/dsr-details?data=15`,
    dsr_description: ['this is dsr 15'],
  },
];
export const DSR_TABLE_COUNT = 15;
